### ISSUE TITLE
Decoupling the tests form the rendering

### ISSUE THREAD

**Issue by Iximiel** [plumed-testcenter/plumed-testcenter#9]
@gtribello I was thinking about this:

Would be a good idea to separate the code for the tests from the code for the rendering of the results?

And left them only coupled by the output?

My idea is that the tests should output a dict, or a yaml file that could be intepreted by anoter script or function that compiles the md files for the site

I think that when the code will be organized like this will be easier to do eventual changes to the webpages without risking to break the tests

What do you think?

**Comment by gtribello** [comment]
Hi @Iximiel 

I am not convinced that this needs doing.  I think that this doesn't really decrease the complexity of the code.  If anything I think it makes it more complicated as you have multiple scripts passing files between them.  I think the priority is to understand why the MD codes are not passing the tests.
